#!/bin/bash

VERSION="$(jq -r .version < package.json)"
#VERSION_PATCH="${VERSION##[0-9.]*.}"
VERSION_MAJOR_MINOR="${VERSION%.[0-9]*}"
VERSION_MINOR="${VERSION_MAJOR_MINOR##[0-9.]*.}"
VERSION_MAJOR="${VERSION_MAJOR_MINOR%.[0-9]*}"

NEW_MINOR="$(($VERSION_MINOR + 1))"

VERSION="$VERSION_MAJOR.$NEW_MINOR.0"

export VERSION

echo "VERSION=$VERSION" >> "$GITHUB_ENV"
