// generated by .defines.ts
// ReSharper disable IdentifierTypo
// ReSharper disable InconsistentNaming

using System;

namespace anatawa12.gists.selector
{
    [Flags]
    enum Define
    {
        None = 0,
        VRCSDK_WORLDS = 1 << 0,
        VRCSDK_AVATARS = 1 << 1,
        VRCSDK_BASE = 1 << 2,
        UDON_SHARP = 1 << 3,
    }

    static class Defines
    {
        public const Define Active = 0
#if VRCSDK_WORLDS
            | Define.VRCSDK_WORLDS
#endif
#if VRCSDK_AVATARS
            | Define.VRCSDK_AVATARS
#endif
#if VRCSDK_BASE
            | Define.VRCSDK_BASE
#endif
#if UDON_SHARP
            | Define.UDON_SHARP
#endif
            ;
        public static bool IsActive(Define define) => (Active & define) == define;
    }
}
