// generated by .defines.ts
// ReSharper disable IdentifierTypo
// ReSharper disable InconsistentNaming

using System;

namespace anatawa12.gists.selector
{
    [Flags]
    enum Define
    {
        None = 0,
        VRCSDK_WORLDS = 1 << 0,
    }

    static class Defines
    {
        public const Define Active = 0
#if VRCSDK_WORLDS
            | Define.VRCSDK_WORLDS
#endif
            ;
        public static bool IsActive(Define define) => (Active & define) == define;
    }
}
